import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface PrivacyModalProps {
  children: React.ReactNode;
}

export function PrivacyModal({ children }: PrivacyModalProps) {
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="text-slate-900">Privacy Policy</DialogTitle>
          <DialogDescription className="text-slate-600">
            How we collect, use, and protect your information
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          <div className="space-y-4 text-sm text-slate-700">
            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Information Collection</h3>
              <p>
                MockEm is a hackathon demonstration project. We collect minimal information necessary for the demo functionality:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Session data for demo usage limits (stored temporarily)</li>
                <li>Optional email addresses for waitlist demonstrations (not actively monitored)</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Data Usage</h3>
              <p>
                This is a demonstration project created for educational purposes. Any data collected is:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Used solely for demo functionality</li>
                <li>Not shared with third parties</li>
                <li>Not used for marketing or commercial purposes</li>
                <li>May be reset or cleared as part of demo maintenance</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Generated Data</h3>
              <p>
                All mock data generated by this tool is entirely fictional and created for testing purposes only. We do not:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Use real personal or business information</li>
                <li>Store generated data beyond the session</li>
                <li>Associate generated data with real individuals or organizations</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Contact</h3>
              <p>
                For questions about this privacy policy or the demo project, reach out on X: 
                <a href="https://x.com/spencer_i_am" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800">
                  @spencer_i_am
                </a>
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Updates</h3>
              <p>
                This privacy policy may be updated as part of the demo project evolution. Last updated: January 2025.
              </p>
            </section>
          </div>
        </ScrollArea>
        <div className="flex justify-end pt-4 border-t">
          <Button onClick={() => setOpen(false)} className="bg-blue-600 hover:bg-blue-700 text-white">
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
