import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";

interface TermsModalProps {
  children: React.ReactNode;
}

export function TermsModal({ children }: TermsModalProps) {
  const [open, setOpen] = useState(false);

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        {children}
      </DialogTrigger>
      <DialogContent className="sm:max-w-2xl max-h-[80vh]">
        <DialogHeader>
          <DialogTitle className="text-slate-900">Terms of Service</DialogTitle>
          <DialogDescription className="text-slate-600">
            Terms and conditions for using this demo project
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          <div className="space-y-4 text-sm text-slate-700">
            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Demo Project Notice</h3>
              <p>
                MockEm is a hackathon submission and demonstration project created for educational and showcase purposes. 
                This is not a commercial service and should be used accordingly.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Acceptable Use</h3>
              <p>By using this demo, you agree to:</p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Use the service for testing and educational purposes only</li>
                <li>Not attempt to overload or abuse the demo system</li>
                <li>Understand this is a demonstration with limited functionality</li>
                <li>Not rely on this service for production or critical use cases</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Generated Data Disclaimer</h3>
              <p>
                All data generated by this tool is entirely fictional. You acknowledge that:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Generated data is for testing purposes only</li>
                <li>No real personal or business information is used</li>
                <li>You will not use generated data to impersonate real individuals or organizations</li>
                <li>Data quality and accuracy are not guaranteed</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Service Availability</h3>
              <p>
                This demo project is provided "as is" without warranties. The service may be:
              </p>
              <ul className="list-disc pl-5 mt-2 space-y-1">
                <li>Temporarily unavailable for maintenance</li>
                <li>Subject to usage limits and restrictions</li>
                <li>Modified or discontinued without notice</li>
                <li>Reset or updated as part of ongoing development</li>
              </ul>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Limitation of Liability</h3>
              <p>
                This is a demonstration project provided for educational purposes. The creator is not liable for any 
                damages or issues arising from use of this demo service.
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Contact</h3>
              <p>
                For questions about these terms or the demo project, reach out on X: 
                <a href="https://x.com/spencer_i_am" target="_blank" rel="noopener noreferrer" className="text-blue-600 hover:text-blue-800">
                  @spencer_i_am
                </a>
              </p>
            </section>

            <section>
              <h3 className="font-semibold text-slate-900 mb-2">Updates</h3>
              <p>
                These terms may be updated as part of the demo project evolution. Last updated: January 2025.
              </p>
            </section>
          </div>
        </ScrollArea>
        <div className="flex justify-end pt-4 border-t">
          <Button onClick={() => setOpen(false)} className="bg-blue-600 hover:bg-blue-700 text-white">
            Close
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
